name: sync-wiki

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]
  gollum:

env:
    GIT_AUTHOR_NAME: quarkusbot
    GIT_AUTHOR_EMAIL: quarkusbot@xam.dk

jobs:
    job-sync-docs-to-wiki:
        runs-on: ubuntu-latest
        if: github.event_name != 'gollum'
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
          - name: Sync docs to wiki
            uses: newrelic/wiki-sync-action@v1.0.1
            with:
              source: docs
              destination: wiki
              token: ${{ secrets.WIKI_PAT }}
              gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
              gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}

    job-sync-wiki-to-docs:
        runs-on: ubuntu-latest
        if: github.event_name == 'gollum'
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.WIKI_PAT }} # allows us to push back to repo
                ref: main
            - name: Sync Wiki to Docs
              uses: newrelic/wiki-sync-action@v1.0.1
              with:
                source: wiki
                destination: docs
                token: ${{ secrets.WIKI_PAT }}
                gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
                gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
                branch: main
